# Generated by Django 3.1.3 on 2020-11-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Standard'), (3, 'High'), (4, 'Critical')], default=2),
        ),
    ]
